import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "用户指南",
      collapsible: false,
      items: [
        "user-guide/quickstart",
        "user-guide/demo-accounts",
        "user-guide/feature-guide",
      ],
    },
    {
      type: "category",
      label: "技术文档",
      collapsible: false,
      items: [
        {
          type: "category",
          label: "模块",
          link: { type: "doc", id: "tech/modules/index" },
          items: [{ type: "autogenerated", dirName: "tech/modules" }],
        },
        {
          type: "category",
          label: "领域",
          link: { type: "doc", id: "tech/domains/index" },
          items: [{ type: "autogenerated", dirName: "tech/domains" }],
        },
        {
          type: "category",
          label: "面试题库",
          link: { type: "doc", id: "tech/interview/index" },
          items: [{ type: "autogenerated", dirName: "tech/interview" }],
        },
      ],
    },
  ],
};

export default sidebars;
